-- Seed plant_types
INSERT INTO plant_types (name, watering_interval, harvest_days, icon) VALUES
('Padi', 3, 90, '🌾'),
('Jagung', 2, 75, '🌽'),
('Kedelai', 3, 80, '🫘'),
('Kacang Tanah', 3, 90, '🥜'),
('Cabe', 1, 90, '🌶️'),
('Tomat', 1, 75, '🍅'),
('Terong', 2, 80, '🍆'),
('Kangkung', 1, 30, '🥬'),
('Bayam', 1, 25, '🥬'),
('Sawi', 1, 40, '🥬'),
('Wortel', 2, 70, '🥕'),
('Bawang Merah', 2, 60, '🧅'),
('Bawang Putih', 3, 90, '🧄'),
('Kentang', 3, 90, '🥔'),
('Ubi Kayu', 7, 240, '🍠'),
('Ubi Jalar', 5, 120, '🍠'),
('Kacang Panjang', 2, 50, '🫛'),
('Labu', 3, 90, '🎃'),
('Mentimun', 1, 60, '🥒'),
('Semangka', 3, 80, '🍉'),
('Melon', 2, 75, '🍈'),
('Stroberi', 1, 90, '🍓'),
('Cabai Rawit', 1, 90, '🌶️'),
('Selada', 1, 40, '🥬'),
('Brokoli', 2, 70, '🥦'),
('Kubis', 2, 90, '🥬'),
('Buncis', 2, 50, '🫛'),
('Timun', 1, 60, '🥒'),
('Lettuce', 1, 40, '🥬'),
('Spinach', 1, 25, '🥬'),
('Carrot', 2, 70, '🥕')
ON CONFLICT (name) DO UPDATE SET
  watering_interval = EXCLUDED.watering_interval,
  harvest_days = EXCLUDED.harvest_days,
  icon = EXCLUDED.icon;
